/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LHeader {
    }
    interface LHero {
    }
}
declare global {
    interface HTMLLHeaderElement extends Components.LHeader, HTMLStencilElement {
    }
    var HTMLLHeaderElement: {
        prototype: HTMLLHeaderElement;
        new (): HTMLLHeaderElement;
    };
    interface HTMLLHeroElement extends Components.LHero, HTMLStencilElement {
    }
    var HTMLLHeroElement: {
        prototype: HTMLLHeroElement;
        new (): HTMLLHeroElement;
    };
    interface HTMLElementTagNameMap {
        "l-header": HTMLLHeaderElement;
        "l-hero": HTMLLHeroElement;
    }
}
declare namespace LocalJSX {
    interface LHeader {
    }
    interface LHero {
    }
    interface IntrinsicElements {
        "l-header": LHeader;
        "l-hero": LHero;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "l-header": LocalJSX.LHeader & JSXBase.HTMLAttributes<HTMLLHeaderElement>;
            "l-hero": LocalJSX.LHero & JSXBase.HTMLAttributes<HTMLLHeroElement>;
        }
    }
}
